### ISSUE TITLE
Infant Error (2)

### ISSUE THREAD

**Issue by Simmisstrait** [CmarNYC-Tools/TS4MorphMaker#2]
Hi, it's me again!
Thanks for making the infant rig!

Unfortunately when I go into minus (-) in the bone morph it doesn't show it in the sims.
I don't really know what it could be because when I go into the minus (-) with a toddler it works, 
in any case it ends up in the sims but not with an infant.

If you want to see my package you can go to this [link](https://simfileshare.net/download/4593689/).

Now I'm more concerned with the problem that it doesn't appear in the sims, I still have to fix the rest of the resizing, etc.

But that becomes difficult if I don't know what to fix, there is little to no tutorial about bone morph for height presets, so for me it is also a matter of finding out what works.
But in my opinion is this a glitch.

**Comment by Simmisstrait** [comment]
> Hi, Can you tell me the specifics of what is not working? Is this a problem with the 3d preview on the "Edit/Create Bone Morph" tab or in game (or both)?

Hi

I create my height preset using the "Edit/Create Bone Morphology" tab.
in the example it shows that it is smaller and it shows that without buggs (for example, if I type -0.6 in the scale form)
But when I create the package for in the sims, and I put the package in my mods folder it shows that it is in the sims.
But it doesn't come into my category of ''body''

This is only for infants.
If I try a toddler and make him smaller in the same way, he falls nicely into the ''body'' category.

**Comment by andrews4s** [comment]
The preset is not tagged for Human. If you tag it for humans, it will show up in the game.

**Comment by Simmisstrait** [comment]
Oh. Stupid me! thank you!!
