### ISSUE TITLE
"The base and morph mesh faces do not match!" and I don't know what to do. Help?

### ISSUE THREAD

**Issue by plasma-tree** [CmarNYC-Tools/TS4MorphMaker#5]
I'm trying to make a slider following this tutorial https://simscommunity.info/2018/07/10/learning-your-tools-the-sims-4-morphmaker/ but whenever i finish what i'm trying to make and export the obj from blender (using the correct version, too) it just gives me this message and when i select "ok", the green loading line never progresses. As in i sat here for 12 hours and it did not progress. can anyone help, please? :( is there something i'm doing wrong? an option i don't have checked?

**Comment by SimplyAnjuta** [comment]
I think this issue can be closed as we solved it on Discord?
